// Generated Arduino code for NodeMCU to serve an HTML page

#include <ESP8266WiFi.h> 
#include <Wire.h>

// WiFi config
const char* ssid = "ColdPalmer";  // WiFi Name
const char* password = "david4567";  // WiFi Password
WiFiServer server(80);

void setup() {
    Serial.begin(9600);
    delay(10);

    // Connecting to WiFi
    Serial.print("Connecting to ");
    Serial.println(ssid); 
    WiFi.begin(ssid, password);
    while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
    }
    Serial.println("");
    Serial.println("WiFi connected");
    server.begin();
    Serial.println("Server started");
    Serial.print("Use this URL to connect: http://");
    Serial.println(WiFi.localIP());
}

void loop() {
    WiFiClient client = server.available();
    if (!client) {
    return;
    }

    Serial.println("New client connected");

    // Send headers
    client.println("HTTP/1.1 200 OK");
    client.println("Content-Type: text/html");
    client.println("Connection: close");
    client.println();

  // Send HTML content
  client.println("<!DOCTYPE html>");
  client.println("<html lang='en'>");
  client.println("");
  client.println("<head>");
  client.println("    <meta charset='UTF-8'>");
  client.println("    <meta name='viewport' content='width=device-width'>");
  client.println("    <meta http-equiv='X-UA-Compatible' content='ie=edge'>");
  client.println("    <link rel='icon' href='https://github.com/sergiocanar/signals_webpage/blob/main/images/favicon.ico'>");
  client.println("    <style>");
  client.println("/* General */");
  client.println("html, body {");
  client.println("    height: 100%;  /* Ensure full height of the viewport */");
  client.println("    margin: 0;");
  client.println("    padding: 0;");
  client.println("    background-color: #F9F5FF;");
  client.println("    font-family: Arial, sans-serif;");
  client.println("    text-align: center; /* Center all text horizontally */");
  client.println("    display: flex;");
  client.println("    flex-direction: column;");
  client.println("}");
  client.println("");
  client.println(".container {");
  client.println("    flex: 1; /* This allows the container to grow and fill the available space */");
  client.println("    padding-bottom: 60px; /* Adjust this to match the footer height */");
  client.println("}");
  client.println("");
  client.println("/* Header */");
  client.println("header {");
  client.println("    background-color: #28262C;");
  client.println("    color: #F9F5FF;");
  client.println("    padding: 20px 0;");
  client.println("}");
  client.println("");
  client.println("/* Sections */");
  client.println("section {");
  client.println("    padding: 20px;");
  client.println("    margin: 20px;");
  client.println("    background-color: #F9F5FF;");
  client.println("    border-radius: 8px;");
  client.println("    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);");
  client.println("}");
  client.println("");
  client.println("h1 {");
  client.println("    margin: 0;");
  client.println("    font-size: 2em;");
  client.println("    color: #28262C;");
  client.println("}");
  client.println("");
  client.println("h2 {");
  client.println("    margin: 0;");
  client.println("    font-size: 1.5em;");
  client.println("    color: #28262C;");
  client.println("}");
  client.println("");
  client.println("");
  client.println("/* Button */");
  client.println("#more-info-button {");
  client.println("    padding: 10px 20px;");
  client.println("    font-size: 1em;");
  client.println("    color: #f7f7f7;");
  client.println("    background-color: #28262C;");
  client.println("    border: none;");
  client.println("    border-radius: 5px;");
  client.println("    cursor: pointer;");
  client.println("    margin-top: 20px;");
  client.println("    display:none;");
  client.println("    margin: auto;");
  client.println("}");
  client.println("");
  client.println("#more-info-button:hover {");
  client.println("    background-color: #14248A;");
  client.println("}");
  client.println("");
  client.println("/* List */");
  client.println("ul {");
  client.println("    list-style-type: none;");
  client.println("    padding: 0;");
  client.println("}");
  client.println("");
  client.println("li {");
  client.println("    margin: 10px 0;");
  client.println("    font-size: 16px;");
  client.println("}");
  client.println("");
  client.println("/* Footer */");
  client.println("#footer {");
  client.println("    position: fixed; /* Keep footer fixed at the bottom */");
  client.println("    bottom: 0;");
  client.println("    width: 100%; /* Full width */");
  client.println("    background-color: #28262C;");
  client.println("    color: white;");
  client.println("    padding: 10px;");
  client.println("    text-align: center;");
  client.println("    z-index: 10; /* Make sure it's above other content */");
  client.println("    overflow-y: auto; /* Enable scrolling if content exceeds the height */");
  client.println("}");
  client.println("");
  client.println("a {");
  client.println("    color: #d7db1c;");
  client.println("}");
  client.println("");
  client.println("a:link, a:visited {");
  client.println("    color: #d4c2fc;");
  client.println("    text-decoration: none;");
  client.println("}");
  client.println("");
  client.println("#ecg-container {");
  client.println("    width: 100%; ");
  client.println("    height: 400px;");
  client.println("}");
  client.println("");
  client.println("#tachogran-container {");
  client.println("    width: 100%;");
  client.println("    height: 400px;");
  client.println("    margin-top: 20px;");
  client.println("}");
  client.println("");
  client.println("");
  client.println("#freq {");
  client.println("    width: 10%;");
  client.println("    margin: 0 auto;");
  client.println("}");
  client.println("</style>");
  client.println("    <link href='https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css' rel='stylesheet' integrity='sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH' crossorigin='anonymous'>");
  client.println("    <script src='https://code.highcharts.com/highcharts.js'></script>");
  client.println("</head>");
  client.println("");
  client.println("<body>");
  client.println("    <div class='container'>");
  client.println("        <div class='row'>");
  client.println("            <h1 id='title'>ECG Visualization</h1>");
  client.println("            <h2 id='subtitle'>Lab 4</h2>");
  client.println("            <figure>");
  client.println("                <img class='img-fluid' src='https://data.org/wp-content/uploads/2022/02/Universidad-de-los-Andes-650x251.png' ");
  client.println("                alt='Universidad de los Andes' style='width: 10%'>");
  client.println("                <figcaption>Departamento de Ingenieria Biomedica</figcaption>");
  client.println("                <hr>");
  client.println("            </figure>");
  client.println("        </div>");
  client.println("        <div class='row'>");
  client.println("            <div class='col-6'>");
  client.println("                <div>");
  client.println("                    <label for='freq'>Frequency: </label>");
  client.println("                    <input type='range' id='freq' min='0' max='100' value='10' step='5'>");
  client.println("                    <span id='freq-display'>10 Hz</span>");
  client.println("                </div>");
  client.println("                <div>");
  client.println("                    <label for='start-point'>Explore ECG: </label>");
  client.println("                    <input type='range' id='start-point' min='0' value='0' step='1'>");
  client.println("                    <span id='start-point-display'>0</span>");
  client.println("                </div>");
  client.println("                <div>");
  client.println("                    <label for='window-size'>Window size (number of data): </label>");
  client.println("                    <input type='range' id='window-size' min='100' value='1' step='1'>");
  client.println("                    <span id='window-size-display'>100</span>");
  client.println("                </div>");
  client.println("            </div>");
  client.println("            <div class='col-6'>");
  client.println("                <div id='bpm-container'>");
  client.println("                    <h3 id='bpm-result'></h3>");
  client.println("                    <h3 id='alert'></h3>");
  client.println("                    <button id='more-info-button' class='btn btn-primary'>Conocer m√°s sobre mi estado</button>");
  client.println("                    <div style='height: 50px;'></div>");
  client.println("                </div>");
  client.println("            </div>");
  client.println("        </div>");
  client.println("        ");
  client.println("        <div class='row'>");
  client.println("            <div id='ecg-container'></div>");
  client.println("        </div>");
  client.println("        <div class='row'>");
  client.println("            <div id='tachogram-container'></div>");
  client.println("        </div>");
  client.println("    </div>");
  client.println("    ");
  client.println("    <footer id='footer'>");
  client.println("        <p>Authors: <a href='https://github.com/sergiocanar'>Sergio Andres Canar Lozano</a> (202020383) and <a href='https://github.com/DavidTobonIBIO'>David Tobon Molina</a> (202123804)</p>");
  client.println("        <p>Source code: <a href='https://github.com/sergiocanar/signals_webpage'>");
  client.println("            https://github.com/sergiocanar/signals_webpage</a></p>");
  client.println("    </footer>");
  client.println("    <script>");
  client.println("");
  client.println("let ecgSignal = [];");
  client.println("let timeArray = [];");
  client.println("let rrIntervals = [];");
  client.println("");
  client.println("");
  client.println("function updateView() {");
  client.println("    ");
  client.println("    let freqVal = parseInt(document.getElementById('freq').value);");
  client.println("    let startPointVal = parseInt(document.getElementById('start-point').value);");
  client.println("    let windowSizeVal = parseInt(document.getElementById('window-size').value);");
  client.println("    ");
  client.println("    document.getElementById('freq-display').innerText = freqVal + ' Hz';");
  client.println("    document.getElementById('start-point-display').innerText = startPointVal;");
  client.println("    document.getElementById('window-size-display').innerText = windowSizeVal;");
  client.println("    ");
  client.println("    updatePlots(freqVal, startPointVal, windowSizeVal);  ");
  client.println("    ");
  client.println("    calculateBPM();");
  client.println("}");
  client.println("");
  client.println("");
  client.println("function setMaxSliderValues(nData) {");
  client.println("    document.getElementById('start-point').max = nData;");
  client.println("    document.getElementById('window-size').max = nData;");
  client.println("}");
  client.println("");
  client.println("");
  client.println("function createECG(sampleRate) {");
  client.println("    ecgSignal = [];");
  client.println("    timeArray = [];");
  client.println("");
  client.println("    const nData = 2000;");
  client.println("    setMaxSliderValues(nData); ");
  client.println("    let height = 200;");
  client.println("    let amplitude = height / 2;");
  client.println("    let start = 0;");
  client.println("    let timePerSample = 1 / sampleRate;");
  client.println("");
  client.println("    let maxAmplitude = amplitude * (0.5 + 0.5 * 0.5);");
  client.println("    for (let i = 0; i < nData; i++) {");
  client.println("        let y = start + maxAmplitude * Math.sin((i / nData) * sampleRate * 2 * Math.PI);");
  client.println("        ecgSignal.push(y);");
  client.println("    }");
  client.println("");
  client.println("    timeArray = Array.from({ length: ecgSignal.length }, (_, i) => parseFloat((i * timePerSample).toFixed(2)));");
  client.println("}");
  client.println("");
  client.println("");
  client.println("");
  client.println("function detectPeaksInWindow(start, end) {");
  client.println("    let peaks = [];");
  client.println("    let window = ecgSignal.slice(start, end);");
  client.println("    let peakValues = window.filter((val, i) =>");
  client.println("        i > 0 && i < window.length - 1 && val > window[i - 1] && val > window[i + 1]");
  client.println("    );");
  client.println("");
  client.println("    if (peakValues.length > 0) {");
  client.println("        let meanVal = mean(peakValues);");
  client.println("        let stdVal = std(peakValues, meanVal);");
  client.println("");
  client.println("        let minThreshold = meanVal + 1 * stdVal;");
  client.println("        let maxThreshold = meanVal + 5 * stdVal;");
  client.println("");
  client.println("        for (let i = 1; i < window.length - 1; i++) {");
  client.println("            if (");
  client.println("                window[i] >= minThreshold &&");
  client.println("                window[i] <= maxThreshold &&");
  client.println("                window[i] > window[i - 1] &&");
  client.println("                window[i] > window[i + 1]");
  client.println("            ) {");
  client.println("                peaks.push(start + i);");
  client.println("            }");
  client.println("        }");
  client.println("    }");
  client.println("    return peaks;");
  client.println("}");
  client.println("");
  client.println("");
  client.println("function detectPeaksWithSlidingWindow(windowSize, step) {");
  client.println("    let allPeaks = [];");
  client.println("");
  client.println("    for (let start = 0; start < ecgSignal.length - windowSize; start += step) {");
  client.println("        let end = start + windowSize;");
  client.println("        let peaks = detectPeaksInWindow(start, end);");
  client.println("        allPeaks.push(...peaks);");
  client.println("    }");
  client.println("");
  client.println("    return { allPeaks, tacoTimeArray: timeArray.slice(allPeaks[1]) };");
  client.println("}");
  client.println("");
  client.println("");
  client.println("function mean(arr) {");
  client.println("    return arr.reduce((sum, value) => sum + value, 0) / arr.length;");
  client.println("}");
  client.println("");
  client.println("");
  client.println("function std(arr, meanVal) {");
  client.println("    let variance = arr.reduce((sum, value) => sum + Math.pow(value - meanVal, 2), 0) / arr.length;");
  client.println("    return Math.sqrt(variance);");
  client.println("}");
  client.println("");
  client.println("");
  client.println("function calculateRRIntervals(peaks, timeArray) {");
  client.println("    rrIntervals = [];");
  client.println("");
  client.println("    for (let i = 1; i < peaks.length; i++) {");
  client.println("        let rr = timeArray[peaks[i]] - timeArray[peaks[i - 1]];");
  client.println("");
  client.println("        ");
  client.println("        if (rr > 0) {");
  client.println("            rrIntervals.push(rr);");
  client.println("        }");
  client.println("    }");
  client.println("}");
  client.println("");
  client.println("");
  client.println("function plotTachogram(timeArray) {");
  client.println("    Highcharts.chart('tachogram-container', {");
  client.println("        chart: { type: 'line' },");
  client.println("        title: { text: 'Tachogram' },");
  client.println("        xAxis: { title: { text: 'Time (seconds)' }, categories: timeArray },");
  client.println("        yAxis: { title: { text: 'RR-interval (seconds)' } },");
  client.println("        series: [{ name: 'RR-interval', data: rrIntervals }]");
  client.println("    });");
  client.println("}");
  client.println("");
  client.println("");
  client.println("function updatePlots(freq, startPoint, windowSize) {");
  client.println("    createECG(freq);");
  client.println("    let signalWindow = ecgSignal.slice(startPoint, startPoint + windowSize);");
  client.println("    let timeWindow = timeArray.slice(startPoint, startPoint + windowSize);");
  client.println("");
  client.println("    Highcharts.chart('ecg-container', {");
  client.println("        chart: { type: 'line' },");
  client.println("        title: { text: 'ECG Signal' },");
  client.println("        xAxis: { title: { text: 'Time (seconds)' }, categories: timeWindow },");
  client.println("        yAxis: { title: { text: 'Amplitude' } },");
  client.println("        series: [{ name: 'ECG Signal', data: signalWindow }]");
  client.println("    });");
  client.println("    let data = detectPeaksWithSlidingWindow(windowSize, 10);");
  client.println("    calculateRRIntervals(data.allPeaks, data.tacoTimeArray);");
  client.println("    plotTachogram(data.tacoTimeArray);");
  client.println("}");
  client.println("");
  client.println("");
  client.println("function calculateBPM() {");
  client.println("    let alertView = document.getElementById('alert');");
  client.println("    let moreInfoButton = document.getElementById('more-info-button');");
  client.println("    if (rrIntervals.length > 0) {");
  client.println("        const avgRRIntervals = rrIntervals.reduce((a, b) => a + b, 0) / rrIntervals.length;");
  client.println("        const bpm = 60 / avgRRIntervals;");
  client.println("");
  client.println("        document.getElementById('bpm-result').innerText = bpm.toFixed(2) + ' BPM';");
  client.println("        ");
  client.println("        moreInfoButton.style.display = 'block'; ");
  client.println("");
  client.println("        if (bpm < 60) {");
  client.println("            alertView.innerText = 'Alert! possible bradycardia.';");
  client.println("            alertView.style.color = 'red';");
  client.println("            moreInfoButton.onclick = () => {");
  client.println("                alert(`La bradicardia es una condiciÛn en la que el corazÛn late m·s despacio de lo normal. Puede ser grave en algunos casos y requerir tratamiento.");
  client.println("");
  client.println("                    Bradicardia leve: 50-60 bpm.");
  client.println("");
  client.println("                    Bradicardia moderada: 40-50 bpm.");
  client.println("                    ");
  client.println("                    Bradicardia severa: Menos de 40 bpm.`);");
  client.println("            };");
  client.println("        } else if (bpm > 100) {");
  client.println("            alertView.innerText = 'Alert! possible tachycardia.';");
  client.println("            alertView.style.color = 'red';");
  client.println("            moreInfoButton.onclick = () => {");
  client.println("                alert(`La taquicardia es una condiciÛn en la que el corazÛn late m·s r·pido de lo normal. Es importante controlarla, ya que puede derivar en problemas m·s serios.");
  client.println("");
  client.println("                    Taquicardia leve: 100-120 bpm.");
  client.println("");
  client.println("                    Taquicardia moderada: 120-150 bpm.");
  client.println("");
  client.println("                    Taquicardia grave: M·s de 150 bpm.`);	");
  client.println("            };");
  client.println("        } else {");
  client.println("            alertView.innerText = 'Within the normal range.';");
  client.println("            alertView.style.color = 'green';");
  client.println("            moreInfoButton.onclick = () => {");
  client.println("                alert('Tu frecuencia cardÌaca est· dentro de los niveles normales. °Sigue asÌ!');");
  client.println("            };");
  client.println("        }");
  client.println("    } else {");
  client.println("        document.getElementById('bpm-result').innerText = 'N/A';");
  client.println("        alertView.innerText = 'Not enough peaks to calculate BPM.';");
  client.println("        alertView.style.color = 'black';");
  client.println("        moreInfoButton.style.display = 'none'; ");
  client.println("    }");
  client.println("}");
  client.println("");
  client.println("");
  client.println("");
  client.println("document.addEventListener('DOMContentLoaded', updateView);");
  client.println("");
  client.println("");
  client.println("let freqSlider = document.getElementById('freq');");
  client.println("freqSlider.oninput = () => updateView();");
  client.println("");
  client.println("let startPointSlider = document.getElementById('start-point');");
  client.println("startPointSlider.oninput = () => updateView();");
  client.println("");
  client.println("let windowSizeSlider = document.getElementById('window-size');");
  client.println("windowSizeSlider.oninput = () => updateView();");
  client.println("</script>");
  client.println("</body>");
  client.println("");
  client.println("</html>");

    client.println();
}
