// Generated Arduino code for NodeMCU to serve an HTML page

#include <ESP8266WiFi.h> 
#include <Wire.h>

// WiFi config
const char* ssid = "ColdPalmer";  // WiFi Name
const char* password = "david4567";  // WiFi Password
WiFiServer server(80);

void setup() {
    Serial.begin(9600);
    delay(10);

    // Connecting to WiFi
    Serial.print("Connecting to ");
    Serial.println(ssid); 
    WiFi.begin(ssid, password);
    while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
    }
    Serial.println("");
    Serial.println("WiFi connected");
    server.begin();
    Serial.println("Server started");
    Serial.print("Use this URL to connect: http://");
    Serial.println(WiFi.localIP());
}

void loop() {
    WiFiClient client = server.available();
    if (!client) {
    return;
    }

    Serial.println("New client connected");

    // Send headers
    client.println("HTTP/1.1 200 OK");
    client.println("Content-Type: text/html");
    client.println("Connection: close");
    client.println();

  // Send HTML content
  client.println("<!DOCTYPE html>");
  client.println("<html lang='en'>");
  client.println("");
  client.println("<head>");
  client.println("    <meta charset='UTF-8'>");
  client.println("    <meta name='viewport' content='width=device-width'>");
  client.println("    <meta http-equiv='X-UA-Compatible' content='ie=edge'>");
  client.println("    <link rel='icon' href='https://drive.google.com/thumbnail?id=1tpmabnom3LA5a4O6Cv9xD30kTTo5dgG0'>");
  client.println("    <style>");
  client.println("html, body {");
  client.println("    height: 100%;");
  client.println("    margin: 0;");
  client.println("    padding: 0;");
  client.println("    background-color: #ffffff;");
  client.println("    font-family: Arial, sans-serif;");
  client.println("    text-align: center;");
  client.println("    display: flex;");
  client.println("    flex-direction: column;");
  client.println("    font-size: 20px;");
  client.println("}");
  client.println("");
  client.println(".container {");
  client.println("    flex: 1;");
  client.println("    padding-bottom: 60px;");
  client.println("}");
  client.println("");
  client.println("header {");
  client.println("    background-color: #28262C;");
  client.println("    color: #F9F5FF;");
  client.println("    padding: 20px 0;");
  client.println("}");
  client.println("");
  client.println("section {");
  client.println("    padding: 20px;");
  client.println("    margin: 20px;");
  client.println("    background-color: #F9F5FF;");
  client.println("    border-radius: 8px;");
  client.println("    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);");
  client.println("}");
  client.println("");
  client.println("h1 {");
  client.println("    margin: 50px;");
  client.println("    font-size: 4em;");
  client.println("    color: #28262C;");
  client.println("}");
  client.println("");
  client.println("h2 {");
  client.println("    margin: 0;");
  client.println("    font-size: 1.5em;");
  client.println("    color: #28262C;");
  client.println("}");
  client.println("");
  client.println("h3 {");
  client.println("    font-size: 15px;");
  client.println("}");
  client.println("");
  client.println("h4 {");
  client.println("    text-align: left;");
  client.println("    font-size: 10px;");
  client.println("}");
  client.println("");
  client.println("p {");
  client.println("    text-align: justify;");
  client.println("    font-size: 25px;");
  client.println("}");
  client.println("");
  client.println("");
  client.println("ul {");
  client.println("    list-style-type: none;");
  client.println("    padding: 0;");
  client.println("}");
  client.println("");
  client.println("li {");
  client.println("    margin: 10px 0;");
  client.println("    font-size: 16px;");
  client.println("}");
  client.println("");
  client.println("ol {");
  client.println("    list-style-type: decimal;");
  client.println("    padding-left: 20px;");
  client.println("    text-align: left;");
  client.println("    margin: 0;    ");
  client.println("}");
  client.println("");
  client.println("ol li {");
  client.println("    margin-bottom: 10px;");
  client.println("    text-decoration: underline;");
  client.println("    font-size: 25px; ");
  client.println("}");
  client.println("");
  client.println("li p {");
  client.println("    margin: 0;");
  client.println("}");
  client.println("");
  client.println("#footer {");
  client.println("    position: relative;");
  client.println("    width: 100%;");
  client.println("    background-color: #28262C;");
  client.println("    color: white;");
  client.println("    text-align: center;");
  client.println("    font-size: 5px;");
  client.println("}");
  client.println("");
  client.println("a {");
  client.println("    color: #d7db1c;");
  client.println("    font-size: 10px;");
  client.println("}");
  client.println("");
  client.println("a:link, a:visited {");
  client.println("    color: #d4c2fc;");
  client.println("    text-decoration: none;");
  client.println("}");
  client.println("");
  client.println("#ecg-container {");
  client.println("    width: 100%; ");
  client.println("    height: 400px;");
  client.println("    margin-bottom: 5%;");
  client.println("}");
  client.println("");
  client.println("#tachogran-container {");
  client.println("    width: 100%;");
  client.println("    height: 500px;");
  client.println("    margin-bottom: 100%;    ");
  client.println("    padding: 100px;");
  client.println("}");
  client.println("");
  client.println("#freq {");
  client.println("    width: 10%;");
  client.println("    margin: auto;");
  client.println("}");
  client.println("");
  client.println(".popup {");
  client.println("    display: none;");
  client.println("    position: fixed;");
  client.println("    z-index: 1000;");
  client.println("    left: 0;");
  client.println("    top: 0;");
  client.println("    width: 100%;");
  client.println("    height: 100%;");
  client.println("    overflow: auto;");
  client.println("    background-color: rgb(0,0,0);");
  client.println("    background-color: rgba(0,0,0,0.4);");
  client.println("}");
  client.println("");
  client.println(".popup-content {");
  client.println("    background-color: #ffffff;");
  client.println("    margin: 15% auto; /* 15% from the top and centered */");
  client.println("    padding: 20px;");
  client.println("    border: 1px solid #888;");
  client.println("    width: 80%; /* Could be more or less, depending on screen size */");
  client.println("    border-radius: 8px;");
  client.println("    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);");
  client.println("}");
  client.println("");
  client.println(".close {");
  client.println("    color: #aaa;");
  client.println("    float: right;");
  client.println("    font-size: 28px;");
  client.println("    font-weight: bold;");
  client.println("}");
  client.println("");
  client.println(".close:hover,");
  client.println(".close:focus {");
  client.println("    color: black;");
  client.println("    text-decoration: none;");
  client.println("    cursor: pointer;");
  client.println("}");
  client.println("");
  client.println("button:hover {");
  client.println("    background-color: #0056b3 !important;");
  client.println("    border-color: #0056b3 !important;");
  client.println("}");
  client.println("");
  client.println(".btn-primary {");
  client.println("    background-color: #14248A !important;");
  client.println("    border-color: #14248A !important;");
  client.println("    margin-top: 20px;");
  client.println("    font-size: 10px;");
  client.println("}");
  client.println("</style>");
  client.println("    <link href='https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css' rel='stylesheet'");
  client.println("        integrity='sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH' crossorigin='anonymous'>");
  client.println("    <script src='https://code.highcharts.com/highcharts.js'></script>");
  client.println("</head>");
  client.println("");
  client.println("<body>");
  client.println("    <div class='container-fluid'>");
  client.println("        <div class='row'>");
  client.println("            <div class='col-4'>");
  client.println("                <figure style='position: absolute; top: 60px; right:70%'>");
  client.println("                    <img class='img-fluid' src='https://drive.google.com/thumbnail?id=1vUv7XzNJbRoR5laaYr--X_C4wTVjqs_K' alt='Universidad de los Andes' style='width: 400px;'>");
  client.println("                </figure>");
  client.println("            </div>");
  client.println("            <div class='col-4'>");
  client.println("                <figure");
  client.println("                    style='position: relative; top: 20px; display: flex; flex-direction: column; align-items: center; margin: 0 auto;'>");
  client.println("                    <img class='img-fluid' src='https://drive.google.com/thumbnail?id=1R8gDDiJrOu39KTVjqC5HQDitdLBYhqvo' alt='Descripción de la imagen'");
  client.println("                        style='width: 50%; margin-bottom: 3%;'>");
  client.println("                </figure>");
  client.println("            </div>");
  client.println("            <div class='col-4'>");
  client.println("                <button class='btn btn-primary' onclick='showPopup()'>");
  client.println("                    ¡Descubre más sobre CardioHub!<br>");
  client.println("                    <span style='display: block; text-indent: 20px;'>Monitoreo inteligente para atletas en");
  client.println("                        evolución.</span>");
  client.println("                </button>");
  client.println("            </div>");
  client.println("            <div id='popup' class='popup'>");
  client.println("                <div class='popup-content'>");
  client.println("                    <span class='close' onclick='closePopup()'>&times;</span>");
  client.println("                    <h2>CardioHub: Monitoreo inteligente para atletas en evolución.</h2>");
  client.println("                    <figure style='position: relative; align-items: center; margin: 0 auto;'>");
  client.println("                        <img class='img-fluid' src='https://drive.google.com/thumbnail?id=1R8gDDiJrOu39KTVjqC5HQDitdLBYhqvo' alt='Descripción de la imagen'");
  client.println("                            style='width: 10%; '>");
  client.println("                    </figure>");
  client.println("                    <h4>Sobre las arritmias y la problemática actual: </h4>");
  client.println("                    <p>La práctica deportiva de alto rendimiento se ha asociado en los últimos años con cardiomiopatías,");
  client.println("                        arritmias ventriculares y enfermedades coronarias, subrayando la importancia de una vigilancia");
  client.println("                        constante");
  client.println("                        tanto durante el ejercicio como en la fase de recuperación [1]. Factores como la deshidratación,");
  client.println("                        alteraciones electrolíticas, estrés fisiológico y fatiga muscular incrementan la susceptibilidad");
  client.println("                        de los");
  client.println("                        atletas a problemas cardíacos, elevando el riesgo de muerte súbita cardíaca (MSC),");
  client.println("                        particularmente en");
  client.println("                        aquellos con afecciones subyacentes no diagnosticadas, como la cardiomiopatía hipertrófica [2].");
  client.println("                        A esto");
  client.println("                        se le suma que la incidencia de MSC es más alta durante o inmediatamente después del ejercicio,");
  client.println("                        lo que");
  client.println("                        refuerza la necesidad de soluciones tecnológicas para monitorear en tiempo real la actividad");
  client.println("                        cardíaca,");
  client.println("                        alertando a los deportistas y entrenadores sobre posibles anormalidades que pongan en peligro la");
  client.println("                        vida");
  client.println("                        [3]. Dentro de las opciones existentes para llevar a cabo un monitoreo constante, el uso de");
  client.println("                        electrocardiogramas (ECG) resulta esencial, ya que permite medir la actividad eléctrica del");
  client.println("                        corazón y");
  client.println("                        detectar arritmias y anomalías en la conducción [4].");
  client.println("                        El proyecto ha sido impulsado por varios incidentes notables en el ámbito deportivo que han");
  client.println("                        subrayado la");
  client.println("                        necesidad urgente de mejorar las herramientas de monitoreo cardíaco para los atletas. Uno de los");
  client.println("                        casos");
  client.println("                        más recientes y reconocidos es el del futbolista Sergio Agüero, quien en 2021 sufrió una");
  client.println("                        arritmia");
  client.println("                        durante un partido, lo que lo obligó a retirarse del fútbol profesional. Este caso no solo");
  client.println("                        demostró las");
  client.println("                        posibles consecuencias de una arritmia no diagnosticada a tiempo, sino que también reveló la");
  client.println("                        necesidad");
  client.println("                        de un monitoreo más riguroso durante la actividad deportiva. Otro ejemplo es el del jugador de");
  client.println("                        fútbol");
  client.println("                        uruguayo Juan Izquierdo, quien falleció a causa de un paro cardiorrespiratorio relacionado con");
  client.println("                        una");
  client.println("                        arritmia mientras entrenaba [5]. Las circunstancias y problemática del monitoreo cardíaco se");
  client.println("                        extienden a");
  client.println("                        otras disciplinas del deporte, ejemplo de esto es el caso del triatleta sudafricano Richard");
  client.println("                        Murray,");
  client.println("                        quien fue diagnosticado con fibrilación auricular en 2021, lo que limitó su rendimiento en esta");
  client.println("                        disciplina. Desde entonces, ha tenido que adaptar su entrenamiento y estilo de vida para");
  client.println("                        gestionar la");
  client.println("                        afección [6].");
  client.println("                    </p>");
  client.println("                    <figure style='position: relative; align-items: center; margin: 0 auto;'>");
  client.println("                        <img class='img-fluid' src='https://i.ibb.co/FqC88ZV/Imagen-inv.png' alt='Descripción de la imagen'");
  client.println("                            style='width: 70%; '>");
  client.println("                    </figure>");
  client.println("                    <h4>Datos estadísticos sobre las arritmias, un problema común en atletas de alto rendimiento: </h4>");
  client.println("                    <p>En cuanto a los datos estadísticos, la arritmia cardiaca tiene una prevalencia global del 1.5% al");
  client.println("                        5%,");
  client.println("                        siendo la fibrilación auricular (FA) su forma más común [7]. En Colombia, se estima que entre el");
  client.println("                        año");
  client.println("                        2013 y 2017, 87 de cada 100,000 habitantes padecían de FA, donde este valor incrementaba a 150");
  client.println("                        en");
  client.println("                        regiones centrales del país [8]. En lo que respecta a los deportistas, se estima que 1 de cada");
  client.println("                        59,452");
  client.println("                        deportistas sufre un paro cardiaco asociado a una arritmia cardiaca, lo que representa 1.7 casos");
  client.println("                        por");
  client.println("                        cada 100,000 atletas [9]. Las estadísticas epidemiológicas también han revelado el alcance del");
  client.println("                        problema.");
  client.println("                        Investigaciones recientes han mostrado que el 12.9% de los corredores de maratón experimentaron");
  client.println("                        arritmias ventriculares durante la carrera [10]. Dichos escenarios muestran el riesgo a la salud");
  client.println("                        y la");
  client.println("                        vida al que pueden llegar a estar expuestos los atletas, además de generar dudas sobre la");
  client.println("                        capacidad");
  client.println("                        actual de los dispositivos de monitoreo para detectar arritmias de manera oportuna durante el");
  client.println("                        ejercicio");
  client.println("                        intenso.");
  client.println("                    </p>");
  client.println("                    <h4>Principales causas que contribuyen al desarrollo de la fisiopatología: </h4>");
  client.println("                    <ol>");
  client.println("                        <li>Suplementos deportivos</li>");
  client.println("                        <p>El uso de suplementos deportivos, especialmente esteroides anaeróbicos, está asociado con un");
  client.println("                            mayor");
  client.println("                            riesgo de FA en atletas jóvenes. Estos productos pueden alterar los mecanismos cardíacos");
  client.println("                            normales,");
  client.println("                            predisponiendo al desarrollo de arritmias [11] </p>");
  client.println("                        <li>Ectopia auricular</li>");
  client.println("                        <p>La FA en deportistas también puede ser provocada por descargas ectópicas focales en las venas");
  client.println("                            pulmonares. Estas descargas son el resultado de un aumento en la actividad simpática debido");
  client.println("                            al");
  client.println("                            ejercicio intenso, lo que puede alterar el ritmo cardíaco normal [11]</p>");
  client.println("                        <li>Inflamación y fibrosis</li>");
  client.println("                        <p>El ejercicio excesivo y el entrenamiento intenso pueden causar inflamación sistémica crónica,");
  client.println("                            manifestada en niveles elevados de proteína C-reactiva. Este proceso inflamatorio, junto con");
  client.println("                            el");
  client.println("                            desarrollo de fibrosis en el tejido cardíaco, crea un ambiente propicio para la aparición de");
  client.println("                            FA, ya");
  client.println("                            que altera la estructura y función normal del corazón [11]</p>");
  client.println("                        <li>Desequilibrio electrolítico</li>");
  client.println("                        <p>El entrenamiento de alta intensidad puede generar cambios significativos en la dinámica de");
  client.println("                            fluidos");
  client.println("                            del cuerpo, lo que conduce a desequilibrios electrolíticos. Estos desequilibrios, como la");
  client.println("                            deshidratación extrema, pueden alterar la función cardíaca y favorecer el desarrollo de FA");
  client.println("                            en los");
  client.println("                            atletas [11].</p>");
  client.println("                    </ol>");
  client.println("                    <h4> CardioHub como wereable, su relevancia para el monitoreo de arritmias en atletas: </h4>");
  client.println("                    <p>El uso de un dispositivo wearable como CardioHub para monitorear en tiempo real la actividad");
  client.println("                        eléctrica");
  client.println("                        del corazón, es crucial para prevenir complicaciones graves en los deportistas. dispositivos");
  client.println("                        permiten la");
  client.println("                        detección temprana de arritmias y proporcionan información precisa sobre el estado cardíaco");
  client.println("                        durante el");
  client.println("                        ejercicio intenso y la recuperación, ayudando a prevenir la muerte súbita cardíaca (MSC). Al");
  client.println("                        proporcionar alertas en tiempo real sobre irregularidades cardíacas, estos wearables permiten a");
  client.println("                        los");
  client.println("                        entrenadores y médicos tomar decisiones rápidas y evitar que las condiciones no diagnosticadas");
  client.println("                        progresen");
  client.println("                        hacia situaciones críticas [12]. Además, el monitoreo continuo ayuda a ajustar las rutinas de");
  client.println("                        entrenamiento de los atletas para optimizar su salud y rendimiento sin comprometer su bienestar");
  client.println("                        cardíaco");
  client.println("                        [13].");
  client.println("                    </p>");
  client.println("                    <p");
  client.println("                        style='font-size: 20px; text-align: center; font-style: italic; font-weight: 550; color: #316bd6;'>");
  client.println("                        CardioHub proporciona una solución innovadora para salvaguardar la salud de los atletas mientras");
  client.println("                        se");
  client.println("                        esfuerzan por alcanzar su máximo rendimiento. La clave está en la prevención, y el monitoreo");
  client.println("                        continuo es");
  client.println("                        la herramienta que garantiza que los corazones de los deportistas sigan latiendo con seguridad y");
  client.println("                        fortaleza.</p>");
  client.println("");
  client.println("                    <figure style='position: relative; align-items: center; margin: 0 auto;'>");
  client.println("                        <img class='img-fluid' src='https://drive.google.com/thumbnail?id=1ezARWMQk74BPl_LAeOS_xsfKKdh7ba7C' alt='Descripción de la imagen'");
  client.println("                            style='width: 30%; '>");
  client.println("                    </figure>");
  client.println("");
  client.println("                    <h4>Referencias</h4>");
  client.println("                    <ol>[1] S. Fyyaz y M. Papadakis, “Arrhythmogenesis of Sports: Myth or Reality?” Arrhythm");
  client.println("                        Electrophysiol Rev,");
  client.println("                        vol. 11, e05, abr. de 2022. DOI: 10.15420/aer.2021.68.</ol>");
  client.println("                    <ol>[2] P. Rao, D. R. Seshadri y J. J. Hsu, “Current and potential applications of wearables in");
  client.println("                        sports");
  client.println("                        cardiology,” Curr. Treat. Options Cardiovasc. Med., vol. 23, n.o 10, oct. de 2021, Accessed Sep.");
  client.println("                        10,");
  client.println("                        2024. direccion: https://doi. ´ org/10.1007/s11936-021-00942-1.</ol>");
  client.println("                    <ol>[3] R. Gajda, J. Gajda, M. Czuba, B. Knechtle y W. Drygas, “Sports heart monitors as reliable");
  client.println("                        diagnostic");
  client.println("                        tools for training control and detecting arrhythmias in professional and leisure-time endurance");
  client.println("                        athletes: An expert consensus statement,” Sports Med., oct. de 2023, Accessed Sep. 10, 2024.");
  client.println("                        direccion:");
  client.println("                        https://doi.org/10. ´ 1007/s40279-023-01948-4.</ol>");
  client.println("                    <ol>[4] D. G. Grazioli, Arritmia ventricular y fibrosis miocardi- ´ ca en atletas, https : / /");
  client.println("                        secardiologia");
  client.println("                        . es / blog / 8298 - arritmia- ventricular- y- fibrosis- miocardica- en- atletas, Accessed: Aug.");
  client.println("                        31,");
  client.println("                        2024.</ol>");
  client.println("                    <ol>[5] H. Y. Izquierdo, La arritmia cardiaca sacude al futbol: ´ el enemigo silencioso de los");
  client.println("                        jugadores");
  client.println("                        tras los casos del ‘Kun’ Aguero y Juan Izquierdo ¨ , https://www.eltiempo.");
  client.println("                        com/deportes/futbol-internacional/la-arritmia-cardiacasacude - al - futbol - el - enemigo -");
  client.println("                        silencioso -");
  client.println("                        de - los - jugadores - tras - los - casos - del - kun - aguero - y - juan - izquierdo-3375588,");
  client.println("                        Accessed:");
  client.println("                        Aug. 31, 2024.</ol>");
  client.println("                    <ol>[6] H. Heidbuchel, “The athlete’s heart is a proarrhythmic heart, and what that means for");
  client.println("                        clinical");
  client.println("                        decision making,” EP Eur., vol. 20, n.o 9, pags. 1401-1411, dic. de ´ 2017, Accessed Sep. 10,");
  client.println("                        2024.");
  client.println("                        direccion: https://doi. ´ org/10.1093/europace/eux294.</ol>");
  client.println("                    <ol>[7] D. S. Desai y S. Hajouli, “Arrhythmias,” en StatPearls, Consultado: el 10 de septiembre de");
  client.println("                        2024,");
  client.println("                        Treasure Island (FL): StatPearls Publishing, 2024. direccion: http: ´");
  client.println("                        //www.ncbi.nlm.nih.gov/books/NBK558923/.</ol>");
  client.println("                    <ol>[8] A. A. Garc ´ ´ıa-Pena et al., “Prevalencia de fibrilaci ˜ on´ auricular en Colombia segun");
  client.println("                        informaci");
  client.println("                        ´ on del Sistema ´ Integral de Informacion de la Protecci ´ on Social (SIS- ´ PRO),” Revista");
  client.println("                        Colombiana");
  client.println("                        de Cardiolog´ıa, vol. 29, n.o 2, pags. 170-176, abr. de 2022. ´ DOI: 10.24875/rccar. m22000139.");
  client.println("                    </ol>");
  client.println("                    <ol>[9] M. Rage et al., “Cardiomyopathy and Sudden Cardiac Death Among the Athletes in Developing");
  client.println("                        Countries:");
  client.println("                        Incidence and Their Prevention Strategies,” Cureus, vol. 15, n.o 2, e35612, 2023. DOI: 10 . 7759");
  client.println("                        /");
  client.println("                        cureus . 35612. </ol>");
  client.println("                    <ol>[10] A. E. V. Toaquiza y D. A. A. T. Aguilar, “Arritmias ventriculares y su relacion con la");
  client.println("                        muerte s ´");
  client.println("                        ubita car- ´ diaca en deportistas,” Ciencia Latina Revista Cient´ıfica Multidisciplinar, vol. 6,");
  client.println("                        n.o 5,");
  client.println("                        nov. de 2022. DOI: 10. 37811/cl rcm.v6i5.3313.</ol>");
  client.println("                    <ol>[11] M. K. Turagam, G. C. Flaker, P. Velagapudi, S. Vadali y M. A. Alpert, “Atrial Fibrillation");
  client.println("                        In");
  client.println("                        Athletes: Pathophysiology, Clinical Presentation, Evaluation and Management,” J Atr");
  client.println("                        Fibrillation, vol.");
  client.println("                        8, n.o 4, pag. 1309, dic. de 2015. ´ DOI: 10.4022/jafib.1309. </ol>");
  client.println("                    <ol>[12] A. Pingitore, M. Peruzzi, S. C. Clarich, Z. Palama,` L. Sciarra y E. Cavarretta, “An");
  client.println("                        overview of");
  client.println("                        the electrocardiographic monitoring devices in sports cardiology: Between present and future,”");
  client.println("                        Clin.");
  client.println("                        Cardiol., jun. de 2023, Accessed Sep. 10, 2024. direccion: https://doi. ´ org/10.1002/clc.24073.");
  client.println("                    </ol>");
  client.println("                    <ol>[13] F. Halabchi, T. Seif-Barghi y R. Mazaheri, “Sudden cardiac death in young athletes; a");
  client.println("                        literature");
  client.println("                        review and special considerations in asia,” Asian J. Sports Medicine, vol. 2, n.o 1, mar. de");
  client.println("                        2011,");
  client.println("                        Accessed Sep. 10, 2024. direccion: https://doi.org/10.5812/asjsm.34818</ol>");
  client.println("");
  client.println("");
  client.println("                </div>");
  client.println("            </div>");
  client.println("            <hr>");
  client.println("            <div class='row'>");
  client.println("                <div class='col-6'>");
  client.println("                    <div>");
  client.println("                        <label for='freq'>Frequency: </label>");
  client.println("                        <input type='range' id='freq' min='0' max='100' value='10' step='5'>");
  client.println("                        <span id='freq-display'>10 Hz</span>");
  client.println("                    </div>");
  client.println("                    <div>");
  client.println("                        <label for='start-point'>Explore ECG: </label>");
  client.println("                        <input type='range' id='start-point' min='0' value='0' step='1'>");
  client.println("                        <span id='start-point-display'>0</span>");
  client.println("                    </div>");
  client.println("                    <div>");
  client.println("                        <label for='window-size'>Window size (number of data): </label>");
  client.println("                        <input type='range' id='window-size' min='100' value='1' step='1'>");
  client.println("                        <span id='window-size-display'>100</span>");
  client.println("                    </div>");
  client.println("                </div>");
  client.println("                <div class='col-6'>");
  client.println("                    <div id='bpm-container'>");
  client.println("                        <h3 id='bpm-result'></h3>");
  client.println("                        <h3 id='alert'></h3>");
  client.println("                    </div>");
  client.println("                </div>");
  client.println("            </div>");
  client.println("            <div class='row'>");
  client.println("                <div class='d-flex justify-content-center'>");
  client.println("                    <button id='more-info-button' class='btn btn-primary'>Get more information about my state</button>");
  client.println("                </div>");
  client.println("                <div style='height: 50px; text-align: center;'></div>");
  client.println("");
  client.println("            </div>");
  client.println("            <div class='row'>");
  client.println("                <div id='ecg-container'></div>");
  client.println("            </div>");
  client.println("            <div class='row'>");
  client.println("                <div id='tachogram-container'></div>");
  client.println("            </div>");
  client.println("        </div>");
  client.println("    </div>");
  client.println("    <footer id='footer' style='text-align: center;'>");
  client.println("        <p style='font-size: 18px; text-align: center; margin-top: 15px;'>");
  client.println("            Authors:");
  client.println("            <a href='https://github.com/sergiocanar' style='font-size: 18px;'>Sergio Andres Canar Lozano</a>");
  client.println("            (202020383),");
  client.println("            <a href='https://github.com/DavidTobonIBIO' style='font-size: 18px;'>David Tobon Molina</a> (202123804),");
  client.println("            <a href='https://github.com/msalcedog' style='font-size: 18px;'>Martin Salcedo</a> (202123644),");
  client.println("            and");
  client.println("            <a href='https://github.com/wilmansh' style='font-size: 18px;'>Wilman Sanchez</a> (202116779) ");
  client.println("        </p>");
  client.println("        <p style='font-size: 18px;text-align: center;'>");
  client.println("            Source code:");
  client.println("            <a href='https://github.com/sergiocanar/signals_webpage' style='font-size: 18px;'>");
  client.println("                https://github.com/sergiocanar/signals_webpage");
  client.println("            </a>");
  client.println("        </p>");
  client.println("    </footer>");
  client.println("    <script>");
  client.println("");
  client.println("let ecgSignal = [];");
  client.println("let timeArray = [];");
  client.println("let rrIntervals = [];");
  client.println("");
  client.println("");
  client.println("function updateView() {");
  client.println("    ");
  client.println("    let freqVal = parseInt(document.getElementById('freq').value);");
  client.println("    let startPointVal = parseInt(document.getElementById('start-point').value);");
  client.println("    let windowSizeVal = parseInt(document.getElementById('window-size').value);");
  client.println("    ");
  client.println("    document.getElementById('freq-display').innerText = freqVal + ' Hz';");
  client.println("    document.getElementById('start-point-display').innerText = startPointVal;");
  client.println("    document.getElementById('window-size-display').innerText = windowSizeVal;");
  client.println("    ");
  client.println("    updatePlots(freqVal, startPointVal, windowSizeVal);");
  client.println("    ");
  client.println("    calculateBPM();");
  client.println("}");
  client.println("");
  client.println("");
  client.println("function setMaxSliderValues(nData) {");
  client.println("    document.getElementById('start-point').max = nData;");
  client.println("    document.getElementById('window-size').max = nData;");
  client.println("}");
  client.println("");
  client.println("");
  client.println("function createECG(sampleRate) {");
  client.println("    ecgSignal = [];");
  client.println("    timeArray = [];");
  client.println("");
  client.println("    const nData = 2000;");
  client.println("    setMaxSliderValues(nData); ");
  client.println("    let height = 200;");
  client.println("    let amplitude = height / 2;");
  client.println("    let start = 0");
  client.println("    let timePerSample = 1 / sampleRate;");
  client.println("");
  client.println("    let maxAmplitude = amplitude * (0.5 + 0.5 * 0.5);");
  client.println("    for (let i = 0; i < nData; i++) {");
  client.println("        let y = start + maxAmplitude * Math.sin((i / nData) * sampleRate * 2 * Math.PI);");
  client.println("        ecgSignal.push(y);");
  client.println("    }");
  client.println("");
  client.println("    timeArray = Array.from({ length: ecgSignal.length }, (_, i) => parseFloat((i * timePerSample).toFixed(2)));");
  client.println("}");
  client.println("");
  client.println("");
  client.println("");
  client.println("function detectPeaksInWindow(start, end) {");
  client.println("    let peaks = [];");
  client.println("    let window = ecgSignal.slice(start, end);");
  client.println("    let peakValues = window.filter((val, i) =>");
  client.println("        i > 0 && i < window.length - 1 && val > window[i - 1] && val > window[i + 1]");
  client.println("    );");
  client.println("");
  client.println("    if (peakValues.length > 0) {");
  client.println("        let meanVal = mean(peakValues);");
  client.println("        let stdVal = std(peakValues, meanVal);");
  client.println("");
  client.println("        let minThreshold = meanVal + 1 * stdVal;");
  client.println("        let maxThreshold = meanVal + 5 * stdVal;");
  client.println("");
  client.println("        for (let i = 1; i < window.length - 1; i++) {");
  client.println("            if (");
  client.println("                window[i] >= minThreshold &&");
  client.println("                window[i] <= maxThreshold &&");
  client.println("                window[i] > window[i - 1] &&");
  client.println("                window[i] > window[i + 1]");
  client.println("            ) {");
  client.println("                peaks.push(start + i);");
  client.println("            }");
  client.println("        }");
  client.println("    }");
  client.println("    return peaks;");
  client.println("}");
  client.println("");
  client.println("");
  client.println("function detectPeaksWithSlidingWindow(windowSize, step) {");
  client.println("    let allPeaks = [];");
  client.println("");
  client.println("    for (let start = 0; start < ecgSignal.length - windowSize; start += step) {");
  client.println("        let end = start + windowSize;");
  client.println("        let peaks = detectPeaksInWindow(start, end);");
  client.println("        allPeaks.push(...peaks);");
  client.println("    }");
  client.println("");
  client.println("    return { allPeaks, tacoTimeArray: timeArray.slice(allPeaks[1]) };");
  client.println("}");
  client.println("");
  client.println("");
  client.println("function mean(arr) {");
  client.println("    return arr.reduce((sum, value) => sum + value, 0) / arr.length;");
  client.println("}");
  client.println("");
  client.println("");
  client.println("function std(arr, meanVal) {");
  client.println("    let variance = arr.reduce((sum, value) => sum + Math.pow(value - meanVal, 2), 0) / arr.length;");
  client.println("    return Math.sqrt(variance);");
  client.println("}");
  client.println("");
  client.println("");
  client.println("function calculateRRIntervals(peaks, timeArray) {");
  client.println("    rrIntervals = [];");
  client.println("");
  client.println("    for (let i = 1; i < peaks.length; i++) {");
  client.println("        let rr = timeArray[peaks[i]] - timeArray[peaks[i - 1]];");
  client.println("");
  client.println("        ");
  client.println("        if (rr > 0) {");
  client.println("            rrIntervals.push(rr);");
  client.println("        }");
  client.println("    }");
  client.println("}");
  client.println("");
  client.println("");
  client.println("function plotTachogram(timeArray) {");
  client.println("    Highcharts.chart('tachogram-container', {");
  client.println("        chart: { type: 'line' },");
  client.println("        title: { text: 'Tachogram' },");
  client.println("        xAxis: { title: { text: 'Time (seconds)' }, categories: timeArray },");
  client.println("        yAxis: { title: { text: 'RR-interval (seconds)' } },");
  client.println("        series: [{ name: 'RR-interval', data: rrIntervals }]");
  client.println("    });");
  client.println("}");
  client.println("");
  client.println("");
  client.println("function updatePlots(freq, startPoint, windowSize) {");
  client.println("    createECG(freq);");
  client.println("    let signalWindow = ecgSignal.slice(startPoint, startPoint + windowSize);");
  client.println("    let timeWindow = timeArray.slice(startPoint, startPoint + windowSize);");
  client.println("");
  client.println("    Highcharts.chart('ecg-container', {");
  client.println("        chart: { type: 'line' },");
  client.println("        title: { text: 'ECG Signal' },");
  client.println("        xAxis: { title: { text: 'Time (seconds)' }, categories: timeWindow },");
  client.println("        yAxis: { title: { text: 'Amplitude' } },");
  client.println("        series: [{ name: 'ECG Signal', data: signalWindow }]");
  client.println("    });");
  client.println("    let data = detectPeaksWithSlidingWindow(windowSize, 10);");
  client.println("    calculateRRIntervals(data.allPeaks, data.tacoTimeArray);");
  client.println("    plotTachogram(data.tacoTimeArray);");
  client.println("}");
  client.println("");
  client.println("");
  client.println("function calculateBPM() {");
  client.println("    let alertView = document.getElementById('alert');");
  client.println("    let moreInfoButton = document.getElementById('more-info-button');");
  client.println("    if (rrIntervals.length > 0) {");
  client.println("        const avgRRIntervals = rrIntervals.reduce((a, b) => a + b, 0) / rrIntervals.length;");
  client.println("        const bpm = 60 / avgRRIntervals;");
  client.println("");
  client.println("        document.getElementById('bpm-result').innerText = bpm.toFixed(2) + ' BPM';");
  client.println("        moreInfoButton.style.display = 'block';");
  client.println("");
  client.println("        if (bpm < 60) {");
  client.println("            alertView.innerText = 'Alert! possible bradycardia.';");
  client.println("            alertView.style.color = 'red';");
  client.println("            moreInfoButton.onclick = function () {");
  client.println("                alert(`Bradycardia is a condition where the heart beats slower than normal. It can be serious in some cases and may require treatment.");
  client.println("                    ");
  client.println("                    Mild bradycardia: 50-60 bpm.");
  client.println("                    ");
  client.println("                    Moderate bradycardia: 40-50 bpm.");
  client.println("                    ");
  client.println("                    Severe bradycardia: Less than 40 bpm.`);");
  client.println("            };");
  client.println("        } else if (bpm > 100) {");
  client.println("            alertView.innerText = 'Alert! possible tachycardia.';");
  client.println("            alertView.style.color = 'red';");
  client.println("            moreInfoButton.onclick = function () {");
  client.println("                alert(`Tachycardia is a condition where the heart beats faster than normal. It is important to monitor it as it can lead to more serious problems.");
  client.println("                    ");
  client.println("                    Mild tachycardia: 100-120 bpm.");
  client.println("                    ");
  client.println("                    Moderate tachycardia: 120-150 bpm.");
  client.println("                    ");
  client.println("                    Severe tachycardia: More than 150 bpm.`);");
  client.println("            };");
  client.println("        } else {");
  client.println("            alertView.innerText = 'Within the normal range.';");
  client.println("            alertView.style.color = 'green';");
  client.println("            moreInfoButton.onclick = function () {");
  client.println("                alert('Your heart rate is within normal levels. Keep it up!');");
  client.println("            };");
  client.println("        }");
  client.println("    } else {");
  client.println("        document.getElementById('bpm-result').innerText = 'N/A';");
  client.println("        alertView.innerText = 'Not enough peaks to calculate BPM.';");
  client.println("        alertView.style.color = 'black';");
  client.println("        moreInfoButton.style.display = 'none';");
  client.println("    }");
  client.println("}");
  client.println("");
  client.println("function showPopup() {");
  client.println("    document.getElementById('popup').style.display = 'block'; ");
  client.println("}");
  client.println("");
  client.println("function closePopup() {");
  client.println("    document.getElementById('popup').style.display = 'none'; ");
  client.println("}");
  client.println("");
  client.println("");
  client.println("window.onclick = function (event) {");
  client.println("    const popup = document.getElementById('popup');");
  client.println("    if (event.target === popup) {");
  client.println("        popup.style.display = 'none';");
  client.println("    }");
  client.println("};");
  client.println("");
  client.println("");
  client.println("document.addEventListener('DOMContentLoaded', updateView);");
  client.println("");
  client.println("");
  client.println("let freqSlider = document.getElementById('freq');");
  client.println("freqSlider.oninput = () => updateView();");
  client.println("");
  client.println("let startPointSlider = document.getElementById('start-point');");
  client.println("startPointSlider.oninput = () => updateView();");
  client.println("");
  client.println("let windowSizeSlider = document.getElementById('window-size');");
  client.println("windowSizeSlider.oninput = () => updateView();");
  client.println("</script>");
  client.println("</body>");
  client.println("");
  client.println("</html>");

    client.println();
}
